sns/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users

  resources :posts

  resources :comments

  resources :user_follows

  resources :user_favorites

  resources :user_joins

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root to: 'toppages#index'

end

sns/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sns/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :content, presence: true, length: { maximum: 255 }

end

sns/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :content, presence: true, length: { maximum: 255 }

  def searching(key_word)
    if key_word
      Post.where(['title OR content LIKE ?', "%#{key_word}%"])
    else
      Post.all
    end
  end

end

sns/app/models/user.rb
class User < ApplicationRecord
  before_save do
    self.email.downcase!
  end

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
            uniqueness: { case_sensitive: false }
  has_secure_password

  mount_uploader :img, ImageUploader

  has_many :posts, :dependent => :destroy

   has_many :user_follows, :dependent => :destroy
    has_many :follows, through: :user_follows, source: :follow
    has_many :user_followeds ,class_name: 'UserFollow', foreign_key: 'follow_id'
    has_many :followeds, through: :user_followeds, source: :user

   has_many :user_favorites, :dependent => :destroy
    has_many :favorites, through: :user_favorites, source: :favorite
    has_many :user_favoriteds ,class_name: 'UserFavorite', foreign_key: 'favorite_id'
    has_many :favoriteds, through: :user_favoriteds, source: :user

  has_many :user_joins, :dependent => :destroy
  has_many :joins, through: :user_joins, source: :join
  has_many :user_joineds, class_name: 'UserJoin', foreign_key: 'join_id'
  has_many :joineds, through: :user_joineds, source: :user


  def follow(user)
      unless self == user || self.follows.exists?(user)
        self.follows << user
      end
    end

    def unfollow(user)
      if self.follows.exists?(user)
        self.follows.destroy(user)
      end
    end

 def favorite(post)
     unless self == post.user || self.favorites.exists?(post)
       self.favorites << post
     end
   end

   def unfavorite(post)
     if self.favorites.exists?(post)
       self.favorites.destroy(post)
     end
   end

  def join(post)
    unless self == post.user || self.joins.exists?(post)
      self.joins << post
    end
  end

  def unjoin(post)
    if self.joins.exists?(post)
      self.joins.destroy(post)
    end
  end


end

sns/app/models/user_favorite.rb
class UserFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :favorite, class_name: 'Post'
end

sns/app/models/user_follow.rb
class UserFollow < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

sns/app/models/user_join.rb
class UserJoin < ApplicationRecord
  belongs_to :user
  belongs_to :join, class_name: 'Post'
end

sns/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper


  private

  def require_login
    unless logged_in?
      redirect_to login_url
    end
  end
end

sns/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 def create
   @post = Post.find_by(id: params[:post_id])
   @comment = @post.comments.build(comment_params)
   if @comment.save
     flash[:success] = "コメントを作成しました"
     redirect_to :back
   else
     flash.now[:danger] = "コメントの作成に失敗しました"
     redirect_to :back
   end
 end

 def destroy
   @comment = Comment.find(params[:id])
   @comment.destroy
   flash[:success] = 'コメントを削除しました。'
   redirect_back(fallback_location: root_path)

 end


  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

sns/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login

  def index
    @posts = Post.searching(params[:key_word])


  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "投稿できました"
      redirect_to posts_path
    else
      flash.now[:danger] = "投稿失敗しました"
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end

  private
  def post_params
    params.require(:post).permit(:content, :img, :title)
  end
end

sns/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

sns/app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

sns/app/controllers/user_favorites_controller.rb
class UserFavoritesController < ApplicationController
 def create
     @post = Post.find(params[:post_id])
     if current_user.favorite(@post)
       flash[:success] = "お気に入りしました"
       redirect_to :back
     else
       flash[:danger] = "お気に入りに失敗しました"
       redirect_to :back
     end

   end

   def destroy
     @post = Post.find(params[:post_id])
     if current_user.unfavorite(@post)
       flash[:success] = "お気に入りを解除しました"
       redirect_to :back
     end
   end
end

sns/app/controllers/user_follows_controller.rb
class UserFollowsController < ApplicationController
 def create
     @user = User.find(params[:user_id])
     if current_user.follow(@user)
       flash[:success] = "フォローしました"
       redirect_to :back
     else
       flash[:danger] = "フォローに失敗しました"
       redirect_to :back
     end

   end

   def destroy
     @user = User.find(params[:user_id])
     if current_user.unfollow(@user)
       flash[:success] = "フォロー解除しました"
       redirect_to :back
     end
   end
end

sns/app/controllers/user_joins_controller.rb
class UserJoinsController < ApplicationController
  def create
      @post = Post.find(params[:post_id])
      if current_user.join(@post)
        flash[:success] = "立候補しました"
        redirect_to message_user_path(@post.user)
      else
        flash[:danger] = "立候補に失敗しました"
        redirect_to :back
      end

    end

    def destroy
      @post = Post.find(params[:post_id])
      if current_user.unjoin(@post)
        flash[:success] = "立候補を解除しました"
        redirect_to :back
      end
    end
end

sns/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:sucess] = "ユーザー編集が完了しました"
      redirect_to @user
    else
      flash[:danger] = "ユーザー編集に失敗しました"
      render :edit
    end


  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :img, :content)
  end
end

sns/app/helpers/application_helper.rb
module ApplicationHelper
end

sns/app/helpers/post_helper.rb
module PostHelper
end

sns/app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

sns/app/helpers/user_favorites_helper.rb
module UserFavoritesHelper

end

sns/app/helpers/user_follows_helper.rb
module UserFollowsHelper
end

sns/app/helpers/user_helper.rb
module UserHelper
end

sns/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

sns/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

sns/app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

sns/app/views/posts/index.html.erb
<h1>Posts#index</h1>

<%= form_tag posts_path, method: :get do %>
  <%= text_field_tag :key_word %>
  <%= submit_tag '検索' %>
<% end %>

<% @posts.each do |post| %>
  <%= post.content %>@<%= post.user.name %>
  <% post.comments.each do |comment| %>
    <%= comment.content %><%= link_to 'コメント削除', comment, method: :delete, data: {confirm: "本当によろしいですか？"} %>
  <% end %>
  <div class="row">
    <aside class="col-md-4">
      <%= form_for(post.comments.build) do |f| %>

        <div class="form-group">
          <%= f.text_field :content, class: 'form-control' %>
        </div>
        <%= hidden_field_tag :post_id, post.id %>
        <%= f.submit 'コメント', class: 'btn btn-primary btn-block' %>
      <% end %>
    </aside>

  </div>
<% end %>

sns/app/views/posts/new.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= form_for(@post) do |f| %>
      <div class="form-group">
        <%= f.text_field :content, class: 'form-control' %>
      </div>
      <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
    <% end %>
  </aside>

</div>

sns/app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

sns/app/views/users/_block_button.html.erb
<% if current_user.blocks.exists?(user) %>
  <%= form_for(current_user.blocks.find_by(id: user.id), url: user_block_path(user), html: {method: :delete}) do |f| %>
    <%= hidden_field_tag :user_id, user.id %>
    <%= f.submit 'ブロック解除' %>
  <% end %>

<% else %>

  <%= form_for(current_user.blocks.build, url: user_blocks_path) do |f| %>
    <%= hidden_field_tag :user_id, user.id %>
    <%= f.submit 'ブロック' %>
  <% end %>
<% end %>

sns/app/views/users/_follow_button.html.erb
<% if current_user.followings.exists?(user) %>
  <%= form_for(current_user.followings.find_by(id: user.id), url: user_follow_path(user), html: {method: :delete}) do |f| %>
    <%= hidden_field_tag :user_id, user.id %>
    <%= f.submit 'フォローを外す' %>
  <% end %>

<% else %>

  <%= form_for(current_user.followings.build, url: user_follows_path) do |f| %>
    <%= hidden_field_tag :user_id, user.id %>
    <%= f.submit 'フォロー' %>
  <% end %>
<% end %>

sns/app/views/users/_mute_button.html.erb
<% if current_user.mutes.exists?(user) %>
  <%= form_for(current_user.mutes.find_by(id: user.id), url: user_mute_path(user), html: {method: :delete}) do |f| %>
    <%= hidden_field_tag :user_id, user.id %>
    <%= f.submit 'ミュートを外す' %>
  <% end %>

<% else %>

  <%= form_for(current_user.mutes.build, url: user_mutes_path) do |f| %>
    <%= hidden_field_tag :user_id, user.id %>
    <%= f.submit 'ミュート' %>
  <% end %>
<% end %>

sns/app/views/users/edit.html.erb
<div class="text-center">
  <h1>Edit</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>

      <div class="form-group">
    <%= f.label :name, 'Name' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

      <div class="form-group">
        <%= f.label :img, 'Image' %>
        <%= f.file_field :img, class: 'form-control' %>
      </div>


      <%= f.submit 'edit', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

sns/app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>

      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>


      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>


      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

sns/app/views/users/show.html.erb
<h1><%= @user.name %></h1>